using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Columns;
using DXApplication9.UserControls;

namespace DXApplication9
{
    public partial class AgrupacionesForm : DevExpress.XtraEditors.XtraForm
    {
        NegocioDataContext AGlobalDataContext = new NegocioDataContext();
        public AgrupacionesForm()
        {
            InitializeComponent();
            //// This line of code is generated by Data Source Configuration Wizard
            //gridControl1.DataSource = globalDataContext.Agrupacion;
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = AGlobalDataContext.Agrupacion;
          //  gridView1.OptionsEditForm.CustomEditFormLayout = new AgrupacionesFormXtraUserControl();
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            AGlobalDataContext.SubmitChanges();
            bindingSource1.DataSource = AGlobalDataContext.Agrupacion;
        }

        private void AgrupacionesForm_FormClosed(object sender, FormClosedEventArgs e)
        {
            var mainForm = (MainForm)MdiParent;
            if (mainForm != null) mainForm.EnableListaAgrupacionesButton(true);
        }

        private void gridView1_EditFormShowing(object sender, DevExpress.XtraGrid.Views.Grid.EditFormShowingEventArgs e)
        {
            PopulaNombreDelGrupo(e.RowHandle);

        }

        private void PopulaNombreDelGrupo(int rowHandled )
        {
            Agrupacion grupo = (Agrupacion)gridView1.GetRow(rowHandled);
            Cobra_repositoryItemLookUpEdit.ForceInitialize();
            Cobra_repositoryItemLookUpEdit.DataSource =
                AGlobalDataContext.AgrupacionDeArtista.Where(
                    c => c.AgrupacionId == grupo.AgrupacionID && c.FechaBaja == null).Select(c => new
                    {
                        NombreCompleto =
                            string.Format("{0} {1} {2}", c.Artista.Nombre.Trim(), c.Artista.PrimerApellido.Trim(),
                                c.Artista.SegundoApellido.Trim())
                    });
            
        
        }

        private void gridView1_Click(object sender, EventArgs e)
        {
            var gridView = gridView1;
            Point clickPoint = gridControl1.PointToClient(MousePosition);
            var hitInfo = gridView.CalcHitInfo(clickPoint);
            if (hitInfo.InRowCell){
                int rowHandle = hitInfo.RowHandle;
                GridColumn column = hitInfo.Column;
                if (column == colNombre_de_Persona_Recibe_Cheque)
                {
                    PopulaNombreDelGrupo(rowHandle);
                }}
        }
            

       

        
    }
}