using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace DXApplication9
{
    public partial class AsignaAgrupacionXtraForm : DevExpress.XtraEditors.XtraForm
    {
        public AsignaAgrupacionXtraForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            this.linqInstantFeedbackSource1.GetQueryable += linqInstantFeedbackSource1_GetQueryable;
            // This line of code is generated by Data Source Configuration Wizard
            this.linqInstantFeedbackSource1.DismissQueryable += linqInstantFeedbackSource1_DismissQueryable;
        }

       


        // This event is generated by Data Source Configuration Wizard
        void linqInstantFeedbackSource1_GetQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {
            
            // Instantiate a new DataContext
            DXApplication9.NegocioDataContext dataContext = new DXApplication9.NegocioDataContext();
            // Assign a queryable source to the LinqInstantFeedbackSource
            e.QueryableSource = dataContext.AgrupacionDeArtista;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissQueryable event handler
            e.Tag = dataContext;
        }

        // This event is generated by Data Source Configuration Wizard
        void linqInstantFeedbackSource1_DismissQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {

            // Dispose of the DataContext
            ((DXApplication9.NegocioDataContext)e.Tag).Dispose();
        }

        
    }
}