using System;
using System.Collections.Generic;
using System.Linq;


namespace DXApplication9
{
    public partial class ConfigFirmasReportesXtraForm : DevExpress.XtraEditors.XtraForm
    {
        NegocioDataContext AGlobalDataContext = new NegocioDataContext();

        public class EnumeradosReporteClass
        {
            public int Key { get; set; }
            public string Descripcion { get; set; }

        }

        public ConfigFirmasReportesXtraForm()
        {
            InitializeComponent();
            ConformaListaEnumeradoDeReportes();
            // This line of code is generated by Data Source Configuration Wizard
            int[] reportes = AGlobalDataContext.ConfigurarPiePorRole.Where(c => c.RoleID == LoginHelper.UsuarioRegistrado.RoleId).Select(c => c.ReporteID).ToArray();
            //reportesBindingSource.DataSource = AGlobalDataContext.Reportes.Where(c=>reportes.Contains(c.IdentificadorReporte));
            
            personasQueFirmanReporteBindingSource.DataSource = AGlobalDataContext.PersonasQueFirmanReporte;
        }

        private void ConformaListaEnumeradoDeReportes()
        {
            List<EnumeradosReporteClass> listaDeEnumeradosClasses = new List<EnumeradosReporteClass>();
            Array descripciones = Enum.GetValues(typeof(Enumerados.Reportes));

            foreach (var descripcion in descripciones)          
            {
                var descripcion1 =
                    ((Enumerados.Reportes) (Enum.Parse(typeof (Enumerados.Reportes), descripcion.ToString())))
                        .StringValue();
                var valor = Convert.ToInt32(Enum.Parse(typeof (Enumerados.Reportes), descripcion.ToString()));
                //TODO verificar en la base de datos si no está en la tabla Reportes el que se corresponde 
                //TODO al identificador y de no estar insertarlo, de lo contrario mantenerlo
                if (!AGlobalDataContext.Reportes.Any(c => c.IdentificadorReporte == valor)){
                    Reportes reporte = new Reportes
                    {Descripcion = descripcion1,
                        IdentificadorReporte = valor,
                        NombreReporte = descripcion.ToString()
                    };
                    AGlobalDataContext.Reportes.InsertOnSubmit(reporte);
                    AGlobalDataContext.SubmitChanges();
                }
                
            }
            reportesBindingSource.DataSource = AGlobalDataContext.Reportes;
        }


        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            AGlobalDataContext.SubmitChanges();
        }
    }
}