using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace DXApplication9
{
    public partial class MonedaXtraForm : DevExpress.XtraEditors.XtraForm
    {
        private NegocioDataContext AGlobalDataContext = (new NegocioDataContext());
        public MonedaXtraForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = AGlobalDataContext.TipoMoneda;
            // This line of code is generated by Data Source Configuration Wizard
        }

        // This event is generated by Data Source Configuration Wizard


        private void gridView1_RowDeleted(object sender, DevExpress.Data.RowDeletedEventArgs e)
        {
            try{
                AGlobalDataContext.SubmitChanges();
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            try
            {
                AGlobalDataContext.SubmitChanges();
            }
            catch (Exception exception)
            {
                var gridView = gridView1;
                XtraMessageBox.Show("Error en la operacion",
                    "Atención", MessageBoxButtons.OK, MessageBoxIcon.Hand);
                gridView.DeleteRow(e.RowHandle);
            }
        }
    }
}