using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;

namespace DXApplication9
{
    
    public partial class PopupParticipanteForm : DevExpress.XtraEditors.XtraForm
    {
         NegocioDataContext _GlobalDataContext = new NegocioDataContext();
        public ParticipantesDeProyectos Participante
        {
           
            
            get
            {
                return new ParticipantesDeProyectos
                {
                   
                    //TODO: Trabajar datos de pasaporte para otros tipos de proyectos
                    // FechaExpedidoPasaporte =!String.IsNullOrEmpty(FechaVencimientoPasaporteDateEdit.Text)?FechaVencimientoPasaporteDateEdit.Text:null,
                    // FechaVencimientoPasaporte = FechaVencimientoPasaporteDateEdit.Text==null?(DateTime?)null:Convert.ToDateTime(FechaVencimientoPasaporteDateEdit.Text),
                    // NumeroDePasaporte = NumeroDePasaporteTextEdit.Text,
                  
                    TipoTramiteMigratorio = TipoTramiteMigratorioLookUpEdit.Text.Trim()
                };
            }
        }
        public PopupParticipanteForm()
        {
            InitializeComponent();
            TipoParticipanteLookUpEdit.Properties.DataSource =
                Enumerados.EnumToList(Enumerados.ProyectoEnumerados.TipoParticipante);
            TipoTramiteMigratorioLookUpEdit.Properties.DataSource =
                Enumerados.EnumToList(Enumerados.ProyectoEnumerados.TipoProyectoMigratorio);
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = _GlobalDataContext.Imagenes;
        }
        
       

        private void InitLocation(Form frm)
        {
            this.Top = frm.Top + (frm.Height - this.Height) / 2;
            this.Left = frm.Left + (frm.Width - this.Width) / 2;
        }

        public void InitData( Form aParentForm,ParticipantesDeProyectos aParticipante)
        {
            InitLocation(aParentForm);
            CarnetIdentidadTextEdit.Text = aParticipante.CarnetIdentidad;
            NombreTextEdit.Text = aParticipante.Nombre;
            PrimerApellidoTextEdit.Text = aParticipante.PrimerApellido;
            SegundoApellidoTextEdit.Text = aParticipante.SegundoApellido;
            NombreAgrupacionTextEdit.Text = aParticipante.NombreAgrupacion;
            FechaExpedidoPasaporteDateEdit.Text = aParticipante.FechaExpedidoPasaporte.ToString();
            FechaVencimientoPasaporteDateEdit.Text = aParticipante.FechaVencimientoPasaporte.ToString();
            NumeroDePasaporteTextEdit.Text = aParticipante.NumeroDePasaporte;
            OcupacionTextEdit.Text = aParticipante.Ocupacion;
            ItemForTipoParticipante.Text = aParticipante.TipoParticipante;
            ItemForTipoTramiteMigratorio.Text = aParticipante.TipoTramiteMigratorio;
        }

      

        private void PopupParticipanteForm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'artistasDataSet.ParticipantesDeProyectos' table. You can move, or remove it, as needed.
           // this.participantesDeProyectosTableAdapter.Fill(this.artistasDataSet.ParticipantesDeProyectos);

        }

        private void buttonEdit1_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.OK;
            Close();
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            _GlobalDataContext.SubmitChanges();}

       
    }
}