using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace DXApplication9
{
    public partial class ResponsabilidadEmpresarioForm : DevExpress.XtraEditors.XtraForm
    {
        NegocioDataContext AGlobalDataContext = new NegocioDataContext();
        public ResponsabilidadEmpresarioForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = AGlobalDataContext.ResponsabilidadEmpresario;
        }

        private void Responsabilidad_gridView_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            try
            {
                AGlobalDataContext.SubmitChanges();
            }
            catch (Exception)
            {
                var gridView = Responsabilidad_gridView;
                XtraMessageBox.Show("Error en la operacion",
                    "Atención", MessageBoxButtons.OK, MessageBoxIcon.Hand);
                    gridView.DeleteRow(e.RowHandle);
            }
        }

        private void NuevoTemasimpleButton_Click(object sender, EventArgs e)
        {
            Responsabilidad_gridView.AddNewRow();}

        private void Responsabilidad_gridView_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            Eliminar_barLargeButtonItem1.Enabled = Responsabilidad_gridView.GetSelectedRows().Any();
        }

        private void Eliminar_barLargeButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                Responsabilidad_gridView.DeleteRow(Responsabilidad_gridView.GetSelectedRows()[0]);
                AGlobalDataContext.SubmitChanges();
            }
            catch (Exception)
            {
                
               // throw;
            }
        }
    }
}